In [8]:
import csv
import numpy as np

# import nyc_taxi.csv as a list of lists
f = open("nyc_taxis.csv", "r")
taxi_list = list(csv.reader(f))

# remove the header row
taxi_list = taxi_list[1:]

# convert all values to floats
converted_taxi_list = []
for row in taxi_list:
    converted_row = []
    for item in row:
        converted_row.append(float(item))
    converted_taxi_list.append(converted_row)

# start writing your code below this comment
taxi = np.array(converted_taxi_list)
print(taxi)

[[2.016e+03 1.000e+00 1.000e+00 ... 1.165e+01 6.999e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 8.000e+00 5.430e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 0.000e+00 3.780e+01 2.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 5.000e+00 6.334e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 8.950e+00 4.475e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 0.000e+00 5.484e+01 2.000e+00]]


In [9]:
taxi_shape = taxi.shape
print(taxi_shape)

(89560, 15)


In [11]:
row_0 = taxi[0]
rows_391_to_500 = taxi[391:501]
row_21_column_5 = taxi[21,5]
print(row_21_column_5)

4.0


In [12]:
cols = [1,4,7]
columns_1_4_7 = taxi[:,cols]
#print(columns_1_4_7)
row_99_columns_5_to_8 = taxi[99,5:9]
print(row_99_columns_5_to_8)
rows_100_to_200_column_14 = taxi[100:201,14]

[   2.      4.     20.91 1744.  ]


In [15]:
fare_amount = taxi[:,9]
fees_amount = taxi[:,10]
fare_and_fees = fare_amount + fees_amount
print(fare_amount)
print(fees_amount)
print(fare_and_fees)

[52.  45.  36.5 ... 52.  34.5 48. ]
[0.8 1.3 1.3 ... 0.8 1.3 1.3]
[52.8 46.3 37.8 ... 52.8 35.8 49.3]


In [16]:
trip_distance_miles = taxi[:,7]
trip_length_seconds = taxi[:,8]

trip_length_hours = trip_length_seconds / 3600 # 3600 seconds is one hour
trip_mph = trip_distance_miles/trip_length_hours

print(trip_length_hours)
print(trip_mph)

[0.56583333 0.42222222 0.40611111 ... 0.78388889 0.30083333 0.47527778]
[37.11340206 38.58157895 31.27222982 ... 22.29907867 42.41551247
 36.90473407]


In [17]:
mph_min = trip_mph.min()
mph_max = trip_mph.max()
mph_mean = trip_mph.mean()
print(mph_max)
print(mph_mean)

82800.0
32.24258580925573


In [18]:
# we'll compare against the first 5 rows only
taxi_first_five = taxi[:5]
# select these columns: fare_amount, fees_amount, tolls_amount, tip_amount
fare_components = taxi_first_five[:,9:13]
# sum the component columns
fare_sums = fare_components.sum(axis=1)
# select the total_amount column
fare_totals = taxi_first_five[:,13]
# compare the summed columns to the fare_totals
print(fare_sums)
print(fare_totals)

[69.99 54.3  37.8  32.76 18.8 ]
[69.99 54.3  37.8  32.76 18.8 ]


In [2]:
import numpy as np
taxi = np.genfromtxt('nyc_taxis.csv', delimiter=',')
taxi_shape = np.shape(taxi)
print(taxi_shape)

(89561, 15)


In [3]:
a = np.array([1, 2, 3, 4, 5])
b = np.array(["blue", "blue", "red", "blue"])
c = np.array([80.0, 103.4, 96.9, 200.3])
a_bool = a < 3
print(a_bool)
b_bool = b == 'blue'
print(b_bool)
c_bool = c > 100
print(c_bool)

[ True  True False False False]
[ True  True False  True]
[False  True False  True]


In [4]:
pickup_month = taxi[:,1]

january_bool = pickup_month == 1
january = pickup_month[january_bool]
january_rides = january.shape[0]

february_bool = pickup_month == 2
february = pickup_month[february_bool]
february_rides = february.shape[0]

print(february_bool)
print(february)
print(february_rides)

[False False False ... False False False]
[2. 2. 2. ... 2. 2. 2.]
13333


In [22]:
tip_amount = taxi[:,12]
tip_bool = tip_amount > 50
top_tips = taxi[tip_bool, 5:14]
print(top_tips)

[[4.0000e+00 2.0000e+00 2.1450e+01 2.0040e+03 5.2000e+01 8.0000e-01
  0.0000e+00 5.2800e+01 1.0560e+02]
 [3.0000e+00 4.0000e+00 9.2000e+00 1.0410e+03 2.7000e+01 1.3000e+00
  5.5400e+00 6.0000e+01 9.3840e+01]
 [2.0000e+00 0.0000e+00 1.9800e+01 1.6710e+03 5.2500e+01 1.3000e+00
  5.5400e+00 5.9340e+01 1.1868e+02]
 [4.0000e+00 2.0000e+00 1.8420e+01 2.9680e+03 5.2000e+01 8.0000e-01
  5.5400e+00 8.0000e+01 1.3834e+02]
 [3.0000e+00 6.0000e+00 4.9000e-01 1.5800e+02 3.5000e+00 1.8000e+00
  0.0000e+00 7.0000e+01 7.5300e+01]
 [2.0000e+00 2.0000e+00 2.7000e+00 3.8100e+02 9.5000e+00 8.0000e-01
  0.0000e+00 6.0000e+01 7.0300e+01]
 [3.0000e+00 4.0000e+00 9.5400e+00 1.2100e+03 2.7500e+01 8.0000e-01
  5.5400e+00 5.5000e+01 8.8840e+01]
 [2.0000e+00 4.0000e+00 1.7600e+01 3.2510e+03 5.2000e+01 8.0000e-01
  5.5400e+00 6.5000e+01 1.2334e+02]
 [4.0000e+00 2.0000e+00 3.8200e+01 9.2520e+03 5.2000e+01 8.0000e-01
  5.5400e+00 8.0000e+01 1.3834e+02]
 [4.0000e+00 2.0000e+00 1.8000e+01 2.2760e+03 1.0000e-02 3.0000e

C:\Users\msgeo\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in greater
  


In [5]:
# this creates a copy of our taxi ndarray
taxi_modified = taxi.copy()
taxi_modified[28214,5] = 1
taxi_modified[:,0] = 16
taxi_modified[1800:1802,7] = taxi_modified[:,7].mean()

In [13]:
# this creates a copy of our taxi ndarray
taxi_copy = taxi.copy()
total_amount = taxi_copy[:,13]
print(total_amount)
amount_bool = total_amount < 0
total_amount[amount_bool] = 0
print(total_amount)

[  nan 69.99 54.3  ... 63.34 44.75 54.84]
[  nan 69.99 54.3  ... 63.34 44.75 54.84]


C:\Users\msgeo\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in less
  """


In [14]:
 # create a new column filled with `0`.
zeros = np.zeros([taxi.shape[0], 1])
taxi_modified = np.concatenate([taxi, zeros], axis=1)
print(zeros)

# array[array[:, column_for_comparison] == value_for_comparison, column_for_assignment] = new_value
taxi_modified[taxi_modified[:, 5] == 2, 15] = 1
taxi_modified[taxi_modified[:, 5] == 3, 15] = 1
taxi_modified[taxi_modified[:, 5] == 5, 15] = 1
print(taxi_modified[:,5])

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[nan  2.  2. ...  2.  2.  2.]


In [17]:
#create new ndarray where six column index equals 2
jfk = taxi[taxi[:, 6] == 2]
jfk_count = jfk.shape[0]

laguardia = taxi[taxi[:, 6] == 3]
laguardia_count = laguardia.shape[0]

newark = taxi[taxi[:, 6] == 5]
newark_count = newark.shape[0]

In [16]:
#Create a new ndarray, cleaned_taxi, containing only rows for which the values of trip_mph are less than 100.
trip_mph = taxi[:,7] / (taxi[:,8] / 3600)
cleaned_taxi = taxi[trip_mph < 100]
mean_distance = cleaned_taxi[:,7].mean()
mean_length = cleaned_taxi[:,8].mean()
mean_total_amount = cleaned_taxi[:,13].mean()

C:\Users\msgeo\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in less
  This is separate from the ipykernel package so we can avoid doing imports until
